---
# This playbook is intended for cleaning up SNMP v2c creds, 
# removing an NMS service account and adding the new SNMP v3 configs

## Run with the '--diff' flag to compare the updated config 
## with the startup config collected in the first play 

- name: Remove old SNMP community strings and add v3 if missing
  hosts: 
  connection: network_cli
  gather_facts: no
  ignore_errors: yes

  tasks:
    - name: Write mem and take a local backup before starting
      ios_config:
        backup: yes
        save_when: always

    - name: Remove SNMPv2c Configs
      ios_config:
        lines:
          - "no snmp-server community xxxxxxx"
          - "no snmp-server community xxxxxxx"
          - "no snmp-server community xxxxxxx"

    - name: Remove old Username
      ios_command:
        commands:
          - command: "conf t"
          - command: "no username xxxxxxx privilege 15 secret"
            prompt: "[confirm]"
            answer: "\r"

    - name: Collect SNMP Configs
      cli_command:
        command: "show run | i snmp-server"
      register: "snmp_results"

    - name: Add SNMPv3 Configs if not present
      ios_config:
        lines:
          - "snmp-server group xxxxxxx v3 priv"
          - "snmp-server user xxxxxxx xxxxxxx v3 auth xxxxxxx xxxxxxx priv xxxxxxx xxxxxxx xxxxxxx"
      when: "'snmp-server group xxxxxxx v3 priv' not in snmp_results.stdout"

    - name: check the startup-config against the running-config
      ios_config:
        diff_against: startup
