---
## Run with the '--diff' flag to compare the startup a running config at the end of the play
- name: Remove Solarwinds SNMP community strings and add v3 if missing
  hosts: 
  connection: network_cli
  gather_facts: no
  ignore_errors: yes

  tasks:
    - name: Write mem and take a local backup before starting
      ios_config:
        backup: yes
        save_when: always

    - name: Remove SNMPv2c Configs
      ios_config:
        lines:
          - "no snmp-server community xxxxxxx"
          - "no snmp-server community xxxxxxx"
          - "no snmp-server community xxxxxxx"

    - name: Remove SW Username
      ios_command:
        commands:
          - command: "conf t"
          - command: "no username xxxxxxx privilege 15 secret"
            prompt: "[confirm]"
            answer: "\r"

    - name: Collect SNMP Configs
      cli_command:
        command: "show run | i snmp-server"
      register: "snmp_results"

    - name: Add SNMPv3 Configs if not present
      ios_config:
        lines:
          - "snmp-server group xxxxxxx v3 priv"
          - "snmp-server user xxxxxxx xxxxxxx v3 auth xxxxxxx xxxxxxx priv xxxxxxx xxxxxxx xxxxxxx"
      when: "'snmp-server group xxxxxxx v3 priv' not in snmp_results.stdout"

    - name: check the startup-config against the running-config
      ios_config:
        diff_against: startup
